language: ruby # ruby version defined in .ruby-version will be used

before_install:
- gem update --system
- gem install bundler

# TODO: Add Azure validation logic
# script:
# - bundle exec rake test

git:
  submodules: false
